M48
; DRILL file {KiCad (6.0.10)} date Mon 09 Jan 2023 23:53:46 GMT
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-01-09T23:53:46+00:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.10)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X151.13Y-125.095
X156.13Y-120.095
X156.13Y-130.095
X158.63Y-120.095
X158.63Y-130.095
T2
X65.532Y-131.382
T0
M30
